# Generated by Django 3.2.16 on 2022-10-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationsView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('prev_reservation_id', models.IntegerField()),
                ('rental_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'rental_app_reservationsview',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS rental_app_reservationsview;
            CREATE OR REPLACE VIEW rental_app_reservationsview AS
            SELECT rl.name AS rental_name, rs.id, rs.checkin, rs.checkout, (SELECT rs2.id
                                                                            FROM rental_app_reservation AS rs2
                                                                            WHERE rl.id = rs2.rental_id
                                                                            AND rs.checkin > rs2.checkout
                                                                            ORDER BY checkout DESC LIMIT 1
                                                                            ) AS prev_reservation_id
            FROM rental_app_rental AS rl
            JOIN rental_app_reservation AS rs
            ON rl.id = rs.rental_id;
            """
        )
    ]
